---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
  - name: student_id
    prompt: "What is your student ID?"
    private: no
 
 
  tasks:
  - name: Add correct student number to VAR file
    lineinfile:
      path: ~/dev/aci/lab1/immday_vars.yml
      regexp: sno
      line: 'student_no: {{student_id}}'
 