---
- name: Disable preferred group in student VRF
  hosts: localhost
  vars_files: immday_vars.yml
  tasks:
  - name: Disable preferred Group 
    aci_rest:
      host: apic1-pod2
      username: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
      password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'
      validate_certs: no
      path: /api/node/mo/uni/tn-sid-student{{ student_no }}/ctx-{{ vrf }}/any.json
      method: post
      content:
        vzAny:
          attributes: 
            dn:  uni/tn-sid-student{{ student_no }}/ctx-{{ vrf }}/any
            prefGrMemb: disabled     
    delegate_to: localhost